"""set delete_at default valut to None

Revision ID: 5d2cea3779a3
Revises: 048aeb0ab200
Create Date: 2026-02-27 17:18:01.285289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d2cea3779a3'
down_revision: Union[str, Sequence[str], None] = '048aeb0ab200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communes', 'deleted_at',
                    existing_type=mysql.DATETIME(),
                    server_default=None,
                    nullable=True
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communes', 'deleted_at',
                    existing_type=mysql.DATETIME(),
                    server_default=sa.text('now()'),
                    nullable=True,
                    )
    # ### end Alembic commands ###
