"""introduce_insee_code

Revision ID: 89a490f20c8c
Revises: 54db70593537
Create Date: 2026-02-27 13:00:14.649975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a490f20c8c'
down_revision: Union[str, Sequence[str], None] = '54db70593537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communes', sa.Column('insee_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'communes', ['insee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communes', type_='unique')
    op.drop_column('communes', 'insee_code')
    # ### end Alembic commands ###
