"""model init

Revision ID: 54db70593537
Revises: 
Create Date: 2026-02-27 11:29:03.012695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54db70593537'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_communes_name'), 'communes', ['name'], unique=False)
    op.create_index(op.f('ix_communes_postal_code'), 'communes', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communes_postal_code'), table_name='communes')
    op.drop_index(op.f('ix_communes_name'), table_name='communes')
    op.drop_table('communes')
    # ### end Alembic commands ###
