"""set delete_at inot nullable

Revision ID: 048aeb0ab200
Revises: b9bcc0a95309
Create Date: 2026-02-27 17:12:59.325619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '048aeb0ab200'
down_revision: Union[str, Sequence[str], None] = 'b9bcc0a95309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communes', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('communes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('communes', 'update_at')
    # ### end Alembic commands ###
